server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-vue-first?serverTimezone=GMT%2b8
    username: root
    password: qwer1234
  servlet:
    multipart:
      max-file-size: 20MB # 默认1MB
      enabled: true
      max-request-size: 200MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #????mybatis?xml??
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
#    path: /home/files/
    path: D:/JAVA/IDEA/IDEAProjects/spring-vue-first/files/